[package]
name = "async-stream"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]
edition = "2018"

[dependencies]
async-stream-impl = { path = "../async-stream-impl" }
futures-core-preview = "=0.3.0-alpha.18"
proc-macro-hack = "0.5.8"

[dev-dependencies]
tokio = "=0.2.0-alpha.2"
tokio-test = "=0.2.0-alpha.2"
futures-util-preview = "=0.3.0-alpha.18"
trybuild = "1.0"
